### ISSUE TITLE
S2-SHIPS Dataset: Sentinel-2 dataset for ship detection

### ISSUE THREAD

**Issue by JannisWolf** [jasonmanesis/Satellite-Imagery-Datasets-Containing-Ships#3]
What a gem of a repo I found here! Thanks for the work put into this amazing summary.

One small dataset I didn't see here is S2-SHIPS, maybe you want to add it:
https://github.com/alina2204/contrastive_SSL_ship_detection

Cheers

**Comment by jasonmanesis** [comment]
Thank you very much. I'm really glad you like it.

Thank you for letting me know, I will try to add it as soon as possible. :)
