### ISSUE TITLE
Accessing FGSD dataset

### ISSUE THREAD

**Issue by kristupas-g** [jasonmanesis/Satellite-Imagery-Datasets-Containing-Ships#5]
Is there another way of accessing the FGSD (Fine-Grained ship detection) dataset other than email? Because I've tried sending an email to the specified recipient but Gmail notified that this address doesn't exist.

**Comment by jasonmanesis** [comment]
In the abstract the authors state "You
are also welcome to contact us at ckyan@bupt.edu.cn to get
the dataset." so I believe there is no other way to access the dataset.
